"""The reference for the crew's records, generated from the code (crew#449, ADR 0014).

What a person or an experiment reads to know what a record's fields mean: the
context every record carries, the kinds of failure, the rules that decide, and
the event names. Written by `crew reference` into `docs/reference/records.md`;
a test regenerates it and compares, so the page and the code can't drift.
"""

from __future__ import annotations

from pathlib import Path

from crew_org.events import EventKind
from crew_org.rules import Kind, Rule, meanings

ROOT = Path(__file__).resolve().parents[2]
PAGE = ROOT / "docs" / "reference" / "records.md"

# What each key of the common context means. Every record carries them where they
# apply: the log's records and the event log's lines under `ctx`; in Grafana, an
# event (from var/telemetry) as `<key>`, and a log line sent over OTLP as `crew_<key>`.
CONTEXT = {
    "tick": "The tick's id, unique across commands. Exported as `service.instance.id` too.",
    "commit": "The crew's commit that ran it. Exported as `service.version` too.",
    "dirty": "Whether the crew's tree had uncommitted changes.",
    "pass": "Which pass of the tick.",
    "phase": "The phase of the pass: refine, deliver, land and so on.",
    "run": "One role's work on one card in one phase. Its records share this id.",
    "role": "The role whose run it is.",
    "card": "The card the work is for.",
    "repo": "The card's repository.",
    "sprint": "The sprint it was in.",
    "attempt": "Which attempt at the card.",
    "for": "What the work was for, where there's no card: a retro, a review of a PR.",
    "trace_id": "The trace it was written in: a log line, an event and a span join on it.",
    "span_id": "The span it was written in.",
}


def _table(rows: dict[str, str], *, head: tuple[str, str]) -> list[str]:
    return [
        f"| {head[0]} | {head[1]} |",
        "|---|---|",
        *(f"| `{k}` | {v} |" for k, v in rows.items()),
    ]


def render() -> str:
    """The reference page, as committed."""
    kinds = meanings(Kind)
    rules = meanings(Rule)
    lines = [
        "# The crew's records: a reference",
        "",
        "Generated by `crew reference` from the code (crew#449). Don't edit it by hand.",
        "",
        "**Records join by ids, never by time or prose.** Every record carries the context",
        "below where it applies. A run's records, model calls and span share its `run`;",
        "a tick's share its `tick` and `commit`.",
        "",
        "## The context every record carries",
        "",
        *_table(CONTEXT, head=("Key", "Meaning")),
        "",
        "## Kinds of failure (`failure_kind`)",
        "",
        'What happened to the work. "Failed" alone reads as a model call failing, and',
        "usually wasn't one (crew#550).",
        "",
        *_table({k.value: kinds[k.name] for k in Kind}, head=("Kind", "Meaning")),
        "",
        "## The rules that decide (`rule`)",
        "",
        "Which of the crew's own rules decided a disposition, a block, a return or a hold.",
        "The record's summary says it for a person; the rule is what a count reads.",
        "",
        *_table({r.value: rules[r.name] for r in Rule}, head=("Rule", "Meaning")),
        "",
        "## Event names",
        "",
        "The event log's kinds, in `var/events/*.jsonl` and mirrored into the log as",
        "`events.<kind>`.",
        "",
        *(f"- `{kind.value}`" for kind in EventKind),
        "",
    ]
    return "\n".join(lines)


def write(path: Path = PAGE) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(), encoding="utf-8")
    return path
